team1/routes.py
from flask import Blueprint, render_template

from .getInformation import getInformation
team1_bp = Blueprint('team1', __name__)

@team1_bp.route('/fullTimeTeacher')
def page1():
    sqlQuery = " SELECT * From shiyan3.teacher t INNER JOIN shiyan3.full_time_teacher f ON t.teacher_id = f.teacher_id;"
    teacherInfo = getInformation(sqlQuery)
    return render_template('team1/full_time_teacher.html', teacherInfo=teacherInfo)

@team1_bp.route('partTimeTeacher')
def page2():
    sqlQuery = """
        SELECT * 
            From shiyan3.teacher t
            INNER JOIN shiyan3.part_time_teacher f
            ON t.teacher_id = f.teacher_id
            ;
    """
    teacherInfo = getInformation(sqlQuery)
    return render_template('team1/part_time_teacher.html', teacherInfo=teacherInfo)

@team1_bp.route('actualStudents')
def page3():
    sqlQuery = "SELECT * From shiyan3.student;"
    studentInfo = getInformation(sqlQuery)
    return render_template('team1/actual_students.html', studentInfo = studentInfo )

@team1_bp.route('student_card/<int:student_id>')
def page4(student_id):
    sqlQuery = "SELECT * FROM shiyan3.student WHERE student_id = %s;"
    student_info= getInformation(student_id, (student_id,))

    return render_template('team1/student_card.html', student_info=student_info[0])

@team1_bp.route('gradStudents')
def page5():
    sqlQuery = "SELECT * From shiyan3.student WHERE category='毕业';"
    studentInfo = getInformation(sqlQuery)
    return render_template('team1/graduated_students.html', studentInfo = studentInfo )

@team1_bp.route('gradStudent_card/<int:student_id>')
def page6(student_id):
    sqlQuery = """
         SELECT * 
        From shiyan3.student s
        INNER JOIN shiyan3.graduated_student g
        ON s.student_id = g.student_id where s.student_id = %s;
    """
    student_info= getInformation(student_id, (student_id,))
    return render_template('team1/grad_student_card.html', student_info=student_info[0])


@team1_bp.route('teacherCourse')
def page7():
    sqlQuery = """
        SELECT c.course_id, c.course_name,c.course_id, c.level,STRING_AGG(t.name, ', ') AS teachers
        FROM shiyan3.course c
        LEFT JOIN shiyan3.teaching_work tw ON c.course_id = tw.course_id
        LEFT JOIN shiyan3.teacher t ON tw.teacher_id = t.teacher_id
        GROUP BY c.course_id, c.course_name,c.course_id, c.level
    """
    courseInfo = getInformation(sqlQuery)

    return render_template('team1/teacher_course.html', courseInfo = courseInfo)

@team1_bp.route('teacherReasearch')
def page8():
    sqlQuery = "SELECT * FROM shiyan3.research_work r INNER JOIN shiyan3.teacher t ON r.teacher_id = t.teacher_id"
    queryInfo = getInformation(sqlQuery)
    return render_template('team1/teacher_research.html', queryInfo = queryInfo )

@team1_bp.route('researchResult')
def page9():
    return render_template('team1/research_result.html')

@team1_bp.route('patentResult')
def page10():
    sqlQuery = "select * from shiyan3.patent"
    queryInfo = getInformation(sqlQuery)
    print(queryInfo[0])
    return render_template('team1/patent_result.html', patentInfo = queryInfo)

@team1_bp.route('textbookResult')
def page11():
    sqlQuery = """
        select t.name, STRING_AGG(tb.name, ',') AS writers 
        FROM shiyan3.textbook t
        JOIN shiyan3.teacher_textbook  tb
        ON tb.textbook_id = t.textbook_id
        GROUP BY t.name; 
        """
    queryInfo = getInformation(sqlQuery)
    return render_template('team1/textbook_result.html', textbookInfo = queryInfo)

@team1_bp.route('reformResult')
def page12():
    return render_template('team1/reformResult.html')


@team1_bp.route('international_information')
def page13():
    return render_template('team1/international_information.html')

templates/team1/actual_students.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">学生信息</div>
        <ul class="sidebar-menu">
            <li class="menu-item">在读学生信息 </li>
            <li class="menu-item">毕业学生信息</li>
        </ul>
</div>

<div class="main-content">
    <h3>在读学生信息</h3>
    <hr class="sep-line">

    <div class="student-content">
        {% for student in studentInfo %}
        <a href="{{ url_for('team1.page4', student_id = student.student_id) }}">
            <div class="student-card">
                <img class="student-photo"src="../../static/images/teacherExample.jpg">
                <p class="student-name">{{ student.name }}</p>
            </div>
        </a>
        
        {% endfor %}
    </div>

</div>
{% endblock %}

templates/team1/full_time_teacher.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">师资队伍</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                
                全职教师
                
            </li>
            <li class="menu-item">
                
                兼职教师
                
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>全职教师</h3>
    <hr class="sep-line">

    {% for teacher in teacherInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/teacherExample.jpg">
            <div class="teacher-information">
                <h3>{{ teacher.name }}</h3>
                <span>职称:</span>
                <span>{{ teacher.title }}</span>
                <br>
                <span>学院:</span>
                <span>{{ teacher.college }}</span>
                <br>
                <span>导师资格:</span>
                <span>{{ teacher.supervisor_qual }}</span>
                <br>
                <span>学历:</span>
                <span>{{ teacher.degree_level }}</span>

                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

templates/team1/grad_student_card.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">学生信息</div>
        <ul class="sidebar-menu">
            <li class="menu-item">在读学生信息 </li>
            <li class="menu-item">毕业学生信息</li>
        </ul>
</div>

<div class="main-content">
    <h3>学生名录</h3>
    <hr class="sep-line">


    <div class="student-information">
        <div class="photo-info">
            <img class="photo-card" src="../../static/images/teacherExample.jpg">
            <p>{{ student_info.program_type }}</p>
            <span>年级：</span>
            <span>{{student_info.grade}}</span>
            <div class="vr"></div>
        </div>
        
        <div clas="info-part">
            
            <h3 class="card-text">学号</h3>
            <p class="content-text">{{ student_info.student_id }}</p>
            <h3 class="card-text">姓名</h3>
            <p class="content-text"> {{ student_info.name }} </p>
      
            <h3 class="card-text">导师</h3>
            <p class="content-text"> {{ student_info.supervisor }}</p>

            <h3 class="card-text">入学时间</h3>
            <p class="content-text"> {{ student_info.enrollment_date }}</p>

            <h3 class="card-text">毕业时间</h3>
            <p class="content-text"> {{ student_info.graduation_date }}</p>
        </div>
    </div>

     
</div>
{% endblock %}

templates/team1/graduated_students.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">学生信息</div>
        <ul class="sidebar-menu">
            <li class="menu-item">在读学生信息 </li>
            <li class="menu-item">毕业学生信息</li>
        </ul>
</div>

<div class="main-content">
    <h3>毕业了学生信息</h3>
    <hr class="sep-line">

    <div class="student-content">
        {% for student in studentInfo %}
        <a href="{{ url_for('team1.page6', student_id = student.student_id) }}">
            <div class="student-card">
                <img class="student-photo"src="../../static/images/teacherExample.jpg">
                <p class="student-name">{{ student.name }}</p>
            </div>
        </a>
        
        {% endfor %}
    </div>

</div>
{% endblock %}

templates/team1/international_information.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">展示国际合作</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                国际合作项目信息 
            </li>

        </ul>
</div>

<div class="main-content">
    <h3>国际合作项目信息 </h3>
    <hr class="sep-line">

        <div class="teacher-card">
            <img class="teacher-photo" src="../../static/images/universities/miandian.jpg">
            <div class="teacher-information">
                <h3>缅甸国立大学</h3>
                <span>所属国家:缅甸</span>
                <br>
                <span>合作项目:人工智能</span>
                <br>
                <span>开始时间:2025/07/12</span>
                <br>
                <span>结束时间时间:2026/05/12</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>

        <div class="teacher-card">
            <img class="teacher-photo" src="../../static/images/universities/tokyo.jpg">
            <div class="teacher-information">
                <h3>东京大学</h3>
                <span>所属国家:日本</span>
                <br>
                <span>合作项目:自动化</span>
                <br>
                <span>开始时间:2026/04/22</span>
                <br>
                <span>结束时间时间:2027/05/12</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>

        <div class="teacher-card">
            <img class="teacher-photo" src="../../static/images/universities/stanford.png">
            <div class="teacher-information">
                <h3>斯坦福大学</h3>
                <span>所属国家:美国</span>
                <br>
                <span>合作项目:软件工程</span>
                <br>
                <span>开始时间:2025/02/12</span>
                <br>
                <span>结束时间时间:2026/05/12</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>
{% endblock %}

templates/team1/part_time_teacher.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">师资队伍</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                
                全职教师
                
            </li>
            <li class="menu-item">
                
                兼职教师
                
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>兼职教师</h3>
    <hr class="sep-line">

    {% for teacher in teacherInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/teacherExample.jpg">
            <div class="teacher-information">
                <h3>{{ teacher.name }}</h3>
                <span>学院:</span>
                <span>{{ teacher.college }}</span>
                <br>
                <span>学历:</span>
                <span>{{ teacher.degree_level }}</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

templates/team1/patent_result.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">研究成果</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                成果  
            </li>
            <li class="menu-item">
                论文
            </li>
            <li class="menu-item">
                教材  
            </li>
            <li class="menu-item">
                教改
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>论文</h3>
    <hr class="sep-line">

    {% for patent in patentInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/classExample.jpg">
            <div class="teacher-information">
                <h3>{{ patent.invention_name }}</h3>
                <span>专利类型:</span>
                <span>{{ patent.patent_type}}</span>
                <br>
                <span>申请日</span>
                <span>{{ patent.application_date }}</span>
                <br>

                <span>授权日:</span>
                <span>{{patent.grant_date}}</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/team1/reform_result.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">研究成果</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                成果  
            </li>
            <li class="menu-item">
                论文
            </li>
            <li class="menu-item">
                教材  
            </li>
            <li class="menu-item">
                教改
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>教改革</h3>
    <hr class="sep-line">

    <h1>目前无有成果</h1>
    
{% endblock %}

templates/team1/research_result.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">研究成果</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                成果  
            </li>
            <li class="menu-item">
                论文
            </li>
            <li class="menu-item">
                教材  
            </li>
            <li class="menu-item">
                教改
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>成果</h3>
    <hr class="sep-line">

    <h1>目前无有成果</h1>
    
{% endblock %}

templates/team1/student_card.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">学生信息</div>
        <ul class="sidebar-menu">
            <li class="menu-item">在读学生信息 </li>
            <li class="menu-item">毕业学生信息</li>
        </ul>
</div>

<div class="main-content">
    <h3>学生名录</h3>
    <hr class="sep-line">


    <div class="student-information">
        <div class="photo-info">
            <img class="photo-card" src="../../static/images/teacherExample.jpg">
            <p>{{ student_info.program_type }}</p>
            <span>年级：</span>
            <span>{{student_info.grade}}</span>
            <div class="vr"></div>
        </div>
        
        <div clas="info-part">
            
            <h3 class="card-text">学号</h3>
            <p class="content-text">{{ student_info.student_id }}</p>
            <h3 class="card-text">姓名</h3>
            <p class="content-text"> {{ student_info.name }} </p>
      
            <h3 class="card-text">导师</h3>
            <p class="content-text"> {{ student_info.supervisor }}</p>
        </div>
    </div>

     
</div>
{% endblock %}

templates/team1/teacher_course.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">教学科研</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                教学工作
            </li>
            <li class="menu-item">
                科研工作            
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>教学工作</h3>
    <hr class="sep-line">

    {% for course in courseInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/classExample.jpg">
            <div class="teacher-information">
                <h3>{{ course.course_name }}</h3>
                <span>课程编号:</span>
                <span>{{ course.course_id }}</span>
                <br>
                <span>学生层次:</span>
                <span>{{ course.level }}</span>
                <br>

                <span>教师:</span>
                <span>{{course.teachers}}</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/team1/teacher_research.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">教学科研</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                教学工作
            </li>
            <li class="menu-item">
                科研工作            
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>科研工作</h3>
    <hr class="sep-line">

    {% for research in queryInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/teacherExample.jpg">
            <div class="teacher-information">
                <h3>{{ research.project_id }}</h3>
                <span>教师:</span>
                <span>{{ research.name }}</span>
                <br>
                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

templates/team1/textbook_result.html
{% extends 'header.html' %}

{% block content %}
<div class="sidebar">
        <div class="sidebar-header">研究成果</div>
        <ul class="sidebar-menu">
            <li class="menu-item">
                成果  
            </li>
            <li class="menu-item">
                论文
            </li>
            <li class="menu-item">
                教材  
            </li>
            <li class="menu-item">
                教改
            </li>
        </ul>
</div>

<div class="main-content">
    <h3>教材</h3>
    <hr class="sep-line">

    {% for textbook in textbookInfo %} 
        <div class="teacher-card">
            <img class="teacher-photo" src="../static/images/classExample.jpg">
            <div class="teacher-information">
                <h3>{{ textbook.name }}</h3>
                <span>作者:</span>
                <span>{{ textbook.writers}}</span>

                <br>
                <hr class="teacher-line">
            </div>
        </div>
    {% endfor %}
{% endblock %}