team1/routes.py
from flask import Blueprint, render_template

from .getInformation import getInformation
team1_bp = Blueprint('team1', __name__)

@team1_bp.route('/fullTimeTeacher')
def page1():
    sqlQuery = " SELECT * From shiyan3.teacher t INNER JOIN shiyan3.full_time_teacher f ON t.teacher_id = f.teacher_id;"
    teacherInfo = getInformation(sqlQuery)
    return render_template('team1/full_time_teacher.html', teacherInfo=teacherInfo)

@team1_bp.route('partTimeTeacher')
def page2():
    sqlQuery = """
        SELECT * 
            From shiyan3.teacher t
            INNER JOIN shiyan3.part_time_teacher f
            ON t.teacher_id = f.teacher_id
            ;
    """
    teacherInfo = getInformation(sqlQuery)
    return render_template('team1/part_time_teacher.html', teacherInfo=teacherInfo)

@team1_bp.route('actualStudents')
def page3():
    sqlQuery = "SELECT * From shiyan3.student;"
    studentInfo = getInformation(sqlQuery)
    return render_template('team1/actual_students.html', studentInfo = studentInfo )

@team1_bp.route('student_card/<int:student_id>')
def page4(student_id):
    sqlQuery = "SELECT * FROM shiyan3.student WHERE student_id = %s;"
    student_info= getInformation(student_id, (student_id,))

    return render_template('team1/student_card.html', student_info=student_info[0])

@team1_bp.route('gradStudents')
def page5():
    sqlQuery = "SELECT * From shiyan3.student WHERE category='毕业';"
    studentInfo = getInformation(sqlQuery)
    return render_template('team1/graduated_students.html', studentInfo = studentInfo )

@team1_bp.route('gradStudent_card/<int:student_id>')
def page6(student_id):
    sqlQuery = """
         SELECT * 
        From shiyan3.student s
        INNER JOIN shiyan3.graduated_student g
        ON s.student_id = g.student_id where s.student_id = %s;
    """
    student_info= getInformation(student_id, (student_id,))
    return render_template('team1/grad_student_card.html', student_info=student_info[0])


@team1_bp.route('teacherCourse')
def page7():
    sqlQuery = """
        SELECT c.course_id, c.course_name,c.course_id, c.level,STRING_AGG(t.name, ', ') AS teachers
        FROM shiyan3.course c
        LEFT JOIN shiyan3.teaching_work tw ON c.course_id = tw.course_id
        LEFT JOIN shiyan3.teacher t ON tw.teacher_id = t.teacher_id
        GROUP BY c.course_id, c.course_name,c.course_id, c.level
    """
    courseInfo = getInformation(sqlQuery)

    return render_template('team1/teacher_course.html', courseInfo = courseInfo)

@team1_bp.route('teacherReasearch')
def page8():
    sqlQuery = "SELECT * FROM shiyan3.research_work r INNER JOIN shiyan3.teacher t ON r.teacher_id = t.teacher_id"
    queryInfo = getInformation(sqlQuery)
    return render_template('team1/teacher_research.html', queryInfo = queryInfo )

@team1_bp.route('researchResult')
def page9():
    return render_template('team1/research_result.html')

@team1_bp.route('patentResult')
def page10():
    sqlQuery = "select * from shiyan3.patent"
    queryInfo = getInformation(sqlQuery)
    print(queryInfo[0])
    return render_template('team1/patent_result.html', patentInfo = queryInfo)

@team1_bp.route('textbookResult')
def page11():
    sqlQuery = """
        select t.name, STRING_AGG(tb.name, ',') AS writers 
        FROM shiyan3.textbook t
        JOIN shiyan3.teacher_textbook  tb
        ON tb.textbook_id = t.textbook_id
        GROUP BY t.name; 
        """
    queryInfo = getInformation(sqlQuery)
    return render_template('team1/textbook_result.html', textbookInfo = queryInfo)

@team1_bp.route('reformResult')
def page12():
    return render_template('team1/reformResult.html')


@team1_bp.route('international_information')
def page13():
    return render_template('team1/international_information.html')

templates/header.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/team1.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    </head>
    <body>
        <header class="header-bar">
            <div class="logo-container">
                <img src="{{ url_for('static', filename='images/bit_logo.png') }}" class="school-logo">
            </div>

            <div class="menu-container">
                <div class="option-container">

                </div>

                <div class="menu">
                    <ul class="nav">
                    <li><a href="#">首页</a></li>
                    <li>
                        <a>关于我们</a>
                        <ul>
                        <li><a href="#">研究所简介</a></li>
                        <li>
                            <a>师资队伍</a>
                            <ul>
                            <li><a href="{{ url_for('team1.page1') }}">全职教师</a></li>
                            <li><a href="{{ url_for('team1.page2') }}">兼职教师</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">学生信息</a>
                            <ul>
                            <li><a href="{{ url_for('team1.page3') }}">在读学生</a></li>
                            <li><a href="{{ url_for('team1.page5') }}">毕业学生</a></li>
                            </ul>
                        </li>
                        <li><a href="#">联系我们</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">动态消息</a>
                        <ul>
                        <li><a href="#">新闻动态</a></li>
                        <li><a href="#">通知通告</a></li>
                        <li><a href="#">学术活动</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>教学科研</a>
                        <ul>
                        <li><a href="{{ url_for('team1.page7') }}">教学工作</a></li>
                        <li><a href="{{ url_for('team1.page8') }}">科研工作</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">研究成果</a>
                        <ul>
                        <li>
                            <a href="#">教学</a>
                            <ul>
                            <li><a href="{{ url_for('team1.page9') }}">成果</a></li>
                            <li><a href="{{ url_for('team1.page10') }}">论文</a></li>
                            <li><a href="{{ url_for('team1.page11') }}">教材</a></li>
                            <li><a href="{{ url_for('team1.page12') }}">教改</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">科研</a>
                            <ul>
                            <li><a href="#">成果</a></li>
                            <li><a href="#">论文</a></li>
                            <li><a href="#">专利</a></li>
                            <li><a href="#">著作权</a></li>
                            </ul>
                        </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">招生信息</a>
                        <ul>
                        <li><a href="#">本科生</a></li>
                        <li><a href="#">硕士生</a></li>
                        <li><a href="#">博士生</a></li>
                        <li><a href="#">留学生</a></li>
                        </ul>
                    </li>
                    <li><a href="{{ url_for('team1.page13') }}">国际合作</a></li>
                    {% if session.get('user_id') %}
                        <li><a href="#">内部管理</a></li>
                        <li><a href="#">下载专区</a></li>
                        <li><a href="#">用户帮助</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>

            <div class="user-area">
                {% if not session.get('user_id') %}
                    <a href="{{ url_for('team3.login_page') }}" class="login-btn">
                        <img src="{{ url_for('static', filename='images/登录.svg') }}" alt="登录" class="login-icon">
                        <span class="login-text">登录/注册</span>
                    </a>
                {% else %}
                    <div class="user-dropdown">
                        <span class="user-info">
                            <img src="{{ url_for('static', filename='images/登录.svg') }}" alt="用户" class="user-icon">
                            <span class="user-name">{{ session.get('chinese_name', '') }}({{ session.get('username', '') }})</span>
                        </span>
                        <div class="block-user"></div>
                        <ul class="child user-menu">
                            <li><a href="{{ url_for('team3.user_center') }}">用户中心</a></li>
                            <li><a href="{{ url_for('team3.logout') }}">登出</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </header>

        <div class="banner-container"></div>
        
        <div class="content">
        {% block content %} {% endblock %}
        </div>

    </body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/team1.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    {% include 'header.html' %}

    
    <div class="presentation-text">研究方向</div>

    <footer>
    </footer>
</body>
</html>

templates/main_page.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/team1.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    {% include 'header.html' %}

    <div class="presentation-container">
        <div class="presentation-card">
            <div class="presentation-title">研究方向</div> 
            <p class="presentation-content">
                网络攻防研究所瞄准国家战略和国防
                安全的重大需求，积极开展计算机网络攻防、
                网络安全、信息对抗等领域的前沿技术研究。
            </p>        
        </div>
        <div class="presentation-card">
            <div class="presentation-title">学术性质</div> 
            <p class="presentation-content">
                兼顾基础研究与应用研究，致力于软件安全工程技术领域的研究与发展。
                以软件安全核心关键技术突破为核心，系统推进软件安全创新技术工具与
                手段的研制及技术推广。研究成果广泛应用于国防、航空航天、公共安全、
                军事国防等国家关键领域，有效保障了嵌入式系统芯片等高安全、低功耗应用的安全性和可靠性   
            </p>        
        </div>
    </div>


    <!-- 视频 -->
    <div class="video-container">
        <div class="news-topic">
            <span>join us</span>
            <div class="news-title">视频传播</div>
            <div class="under_line_1"></div>
        </div>

        <video class="presentation-video" controls>
            <source src="" type="video/mp4">
        </video>
    </div>
    </div>

    <!-- 新闻 -->
     <div class="news-container">
        <div class="news-card">
            <div class="news-topic">
                <span>news</span>
                <div class="news-title">新闻动态</div>
                <div class="under_line_1"></div>
            </div>

            <div class="news">
                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="news-card">
            <div class="news-topic">
                <span>notice</span>
                <div class="news-title">通知通告</div>
                <div class="under_line_1"></div>
            </div>

            <div class="news">
                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="news-card">
            <div class="news-topic">
                <span>events</span>
                <div class="news-title">学术活动</div>
                <div class="under_line_1"></div>
            </div>

            <div class="news">
                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>

                <div class="actual-news">
                    <div class="day-card">
                         <div class="day">26</div>
                        <div class="day_month">2024.12.10</div>
                    </div>
                    <div>
                        <div class="news-text">【国际会议】计算机视觉国际会议预报名通知</div>
                        <div>将于2025年3月在上海举行，现已开放早鸟注册。</div>
                    </div>
                </div>
            </div>
        </div>
        
     </div>

    <div class="links">
        <span class="link"><a href="http://cs.bit.edu.cn">计算机学院</a></span>
        <span class="link"><a href="http://grd.bit.edu.c">研究生院 </a></span>
        <span class="link"><a href="http://grdms.bit.edu.cn">研究生管理系统</a></span>
    </div>
    
    <footer>
        <p>© db_7 | 研究所网站前端展示部分</p>
    </footer>
</body>
</html>